CREATE TABLE Members (
    MemberID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    ActiveLoans INT DEFAULT 0
);

CREATE TABLE Books (
    BookID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ISBN VARCHAR(20) UNIQUE NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Author VARCHAR(100),
    IsAvailable BOOLEAN DEFAULT TRUE
);

CREATE TABLE Loans (
    LoanID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BookID INT NOT NULL,
    MemberID INT NOT NULL,
    LoanDate DATE DEFAULT CURRENT_DATE,
    ReturnDate DATE,
    FOREIGN KEY (BookID) REFERENCES Books(BookID),
    FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
);

CREATE INDEX idx_books_isbn ON Books(ISBN);
CREATE INDEX idx_loans_member ON Loans(MemberID);
CREATE INDEX idx_loans_returndate ON Loans(ReturnDate);
